-- MySQL Script generated by MySQL Workbench
-- Fri Apr 12 13:27:25 2019
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema strascook
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema strascook
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `strascook` DEFAULT CHARACTER SET utf8 ;
USE `strascook` ;

-- -----------------------------------------------------
-- Table `strascook`.`user`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `strascook`.`user` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `firstname` VARCHAR(80) NULL DEFAULT NULL,
  `adress` VARCHAR(80) NULL DEFAULT NULL,
  `phone` VARCHAR(12) NULL DEFAULT NULL,
  `email` VARCHAR(45) NULL DEFAULT NULL,
  `lastname` VARCHAR(45) NULL DEFAULT NULL,
  `city` VARCHAR(80) NULL DEFAULT NULL,
  `zip` INT(11) NULL DEFAULT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `strascook`.`email`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `strascook`.`email` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `email` VARCHAR(255) NULL DEFAULT NULL,
  `user_id` INT(11) NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_email_user1` (`user_id` ASC),
  CONSTRAINT `fk_email_user1`
    FOREIGN KEY (`user_id`)
    REFERENCES `strascook`.`user` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `strascook`.`price`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `strascook`.`price` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `price` INT(11) NULL DEFAULT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 3
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `strascook`.`menus`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `strascook`.`menus` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `name` TEXT NULL DEFAULT NULL,
  `starter` TEXT NULL DEFAULT NULL,
  `main_course` TEXT NULL DEFAULT NULL,
  `dessert` TEXT NULL DEFAULT NULL,
  `description` TEXT NULL DEFAULT NULL,
  `price_id` INT(11) NOT NULL,
  PRIMARY KEY (`id`),
  CONSTRAINT `fk_menus_price`
    FOREIGN KEY (`price_id`)
    REFERENCES `strascook`.`price` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
AUTO_INCREMENT = 4
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `strascook`.`images`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `strascook`.`images` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `img_src` VARCHAR(255) NULL DEFAULT NULL,
  `thumb` TINYINT(4) NULL DEFAULT NULL,
  `img_menu` INT NULL,
  `menus_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  CONSTRAINT `fk_images_menus1`
    FOREIGN KEY (`menus_id`)
    REFERENCES `strascook`.`menus` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
AUTO_INCREMENT = 11
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `strascook`.`reservation`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `strascook`.`reservation` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `status` TINYINT(4) NULL DEFAULT NULL,
  `user_id` INT(11) NOT NULL,
  `date_passed` DATETIME NULL DEFAULT CURRENT_TIMESTAMP,
  `date_booked` DATETIME NULL DEFAULT NULL,
  `reservationcol` VARCHAR(45) NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  CONSTRAINT `fk_reservation_user1`
    FOREIGN KEY (`user_id`)
    REFERENCES `strascook`.`user` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `strascook`.`order`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `strascook`.`order` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `quantity` VARCHAR(45) NULL DEFAULT NULL,
  `menus_id` INT(11) NOT NULL,
  `reservation_id` INT(11) NOT NULL,
  PRIMARY KEY (`id`),
  CONSTRAINT `fk_order_menus1`
    FOREIGN KEY (`menus_id`)
    REFERENCES `strascook`.`menus` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_order_reservation1`
    FOREIGN KEY (`reservation_id`)
    REFERENCES `strascook`.`reservation` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `strascook`.`partenaire`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `strascook`.`partenaire` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `url` VARCHAR(255) NULL DEFAULT NULL,
  `title` VARCHAR(45) NULL DEFAULT NULL,
  `description` TEXT NULL DEFAULT NULL,
  `logo_src` VARCHAR(255) NULL DEFAULT NULL,
  `thum_src` VARCHAR(255) NULL DEFAULT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
